apiVersion: v1
kind: Service
metadata:
  name: Services
spec:
  selector:
  - name: eshwar
    surname: kodavali
    age: "21"
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port